DROP TABLE IF EXISTS handling CASCADE;
DROP TABLE IF EXISTS interactions CASCADE;
DROP TABLE IF EXISTS hotels CASCADE;


-- LOAD HOTELS (monthly 2025)

COPY hotels
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/hotels_25_01.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

-- LOAD INTERACTIONS (monthly 2025)

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_01.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_02.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_03.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_04.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_05.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_06.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_07.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_08.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_09.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_10.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_11.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY interactions
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/interactions_25_12.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

-- LOAD HEADLING (monthly 2025)

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_01.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_02.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_03.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_04.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_05.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_06.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_07.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_08.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_09.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_10.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_11.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY handling
FROM 'F:/ALMACENAMIENTO/DATA ANALITYCS/PORTAFOLIO/AI_Assistant_Hotels/CSV/handling_25_12.csv'
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');